#!/bin/bash
clear

source /usr/bin/ui.sh

eval "$(wget -qO- "https://drive.google.com/u/4/uc?id=1eutPTYsea7xYx1mNBWDQ_g1Yx3ZPNimF")"

MYIP=$(curl -s https://ipinfo.io/ip?token=4e159274f1da8c)

data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
exp=$(curl -sS $IZIN | grep $MYIP | awk '{print $3}')
IPCLIENT=$(curl -sS $IZIN | grep $MYIP | awk '{print $4}')

if [[ "$MYIP" != "$IPCLIENT" ]]; then
  rejected "$MYIP"
else
  if [[ $date_list > $exp ]] then
    rejected "$MYIP"
  fi
fi

CITY=$(cat /etc/xray/city)
ISP=$(cat /etc/xray/isp)
DOMAIN=$(cat /etc/xray/domain)
NAME=$(cat /etc/xray/username)

if [ ! -e /usr/local/bin/reboot_otomatis ]; then
  echo '#!/bin/bash' > /usr/local/bin/reboot_otomatis 
  echo 'tanggal=$(date +"%m-%d-%Y")' >> /usr/local/bin/reboot_otomatis 
  echo 'waktu=$(date +"%T")' >> /usr/local/bin/reboot_otomatis 
  echo 'echo "Sucsesfully Reboot On $tanggal Time $waktu." >> /root/log-reboot.txt' >> /usr/local/bin/reboot_otomatis 
  echo '/sbin/shutdown -r now' >> /usr/local/bin/reboot_otomatis 
  chmod +x /usr/local/bin/reboot_otomatis
fi

echo -e ""
banner "AUTOREBOOT MANAGER"
echo -e "  ${GREEN}1. ${WHITE}${BOLD}Set Auto-Reboot 12 Hour Period${RESET}"
echo -e "  ${GREEN}2. ${WHITE}${BOLD}Set Auto-Reboot 1 Day Period${RESET}"
echo -e "  ${GREEN}3. ${WHITE}${BOLD}Set Auto-Reboot 1 Week Period${RESET}"
echo -e "  ${GREEN}4. ${WHITE}${BOLD}Set Auto-Reboot 1 Month Period${RESET}"
echo -e "  ${GREEN}5. ${WHITE}${BOLD}Deactivate Auto-Reboot${RESET}"
echo -e "  ${GREEN}6. ${WHITE}${BOLD}See Reboot Log${RESET}"
echo -e "  ${GREEN}7. ${WHITE}${BOLD}Delete Reboot Log${RESET}"
echo -e "  ${GREEN}0. ${RED}${BOLD}}BACK TO EXIT MENU ${RESET}"
garis
echo -e ""

pesan() {
  msg_info "Autoreboot Successfully set $1 Period"
  read -n 1 -s -r -p "Press any key to back on menu"
  autoreboot
}

while true; do
  read -p " Select menu : " opt
  case $opt in
    1 | 01)
      clear
      echo "10 */12 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
      pesan "12 Hour"
    break ;;
    2 | 02)
      clear
      echo "0 0 * * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
      pesan "1 Day"
    break ;;
    3 | 03)
      clear
      echo "10 0 */7 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
      pesan "1 Week"
    break ;;
    4 | 04)
      clear
      echo "10 0 1 * * root /usr/local/bin/reboot_otomatis" > /etc/cron.d/reboot_otomatis
      pesan "1 Mounth"
    break ;;
    5 | 05)
      clear
      rm -f /etc/cron.d/reboot_otomatis
      msg_info "Autoreboot deactived"
      read -n 1 -s -r -p "Press any key to back on menu"
      autoreboot
    break ;;
    6 | 06)
      clear
      if [ ! -e /root/log-reboot.txt ]; then
      	msg_info "No Activity Found"
      else 
        banner "AUTOREBOOT LOGS"
        cat /root/log-reboot.txt
        garis
      fi
      read -n 1 -s -r -p "Press any key to back on menu"
      autoreboot
    break ;;
    7 | 07)
      clear
      echo "" > /root/log-reboot.txt
      msg_info "Autoreboot log deleted"
      read -n 1 -s -r -p "Press any key to back on menu"
      autoreboot
    break ;;
    0 | 00)
      clear
      menu
    break ;;
    *)
      tput cuu 1 && tput el 
      tput cuu 1 && tput el 
      echo -e "\nInput tidak valid! Silakan coba lagi."
      sleep 2
      tput cuu 1 && tput el  
    ;;
  esac
  tput cuu 1 && tput el  
  read -p "Tekan Enter untuk kembali ke menu..."
  tput cuu 1 && tput el  # Hapus pesan error sebelum kembali ke input
done