#!/bin/bash
clear

source /usr/bin/ui.sh

echo -n >/tmp/other.txt
data=($(cat /etc/xray/config.json | grep '^#!#' | cut -d ' ' -f 2 | sort | uniq))
garis
center "SHADOWSOCKS USER LOGIN"
garis
for akun in "${data[@]}"; do
  if [[ -z "$akun" ]]; then
    akun="tidakada"
  fi
  
  echo -n >/tmp/ipshadowsocks.txt
  data2=($(cat /var/log/xray/access.log | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | sort | uniq))
  for ip in "${data2[@]}"; do
    jum=$(cat /var/log/xray/access.log | grep -w "$akun" | tail -n 500 | cut -d " " -f 3 | sed 's/tcp://g' | cut -d ":" -f 1 | grep -w "$ip" | sort | uniq)
    if [[ "$jum" = "$ip" ]]; then
      echo "$jum" >>/tmp/ipshadowsocks.txt
    else
      echo "$ip" >>/tmp/other.txt
    fi
    jum2=$(cat /tmp/ipshadowsocks.txt)
    sed -i "/$jum2/d" /tmp/other.txt >/dev/null 2>&1
  done
  
  jum=$(cat /tmp/ipshadowsocks.txt)
  if [[ -z "$jum" ]]; then
    echo >/dev/null
  else
    jum2=$(cat /tmp/ipshadowsocks.txt | nl)
    echo "user : $akun"
    echo "$jum2"
    garis
  fi
  rm -rf /tmp/ipshadowsocks.txt
done

rm -rf /tmp/other.txt
garis
echo ""
read -p "Enter Back To Menu"
menu