#!/bin/bash
clear

source /usr/bin/ui.sh

systemctl reload ssh
if [ -e "/var/log/auth.log" ]; then
  LOG="/var/log/auth.log";
fi
if [ -e "/var/log/secure" ]; then
  LOG="/var/log/secure.log";
fi

data=( `ps aux | grep -i dropbear | awk '{print $2}'`);
garis
echo -e "  ${WHITE}  ID  |  Username  |  IP Address ${RESET}"
garis

cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" > /tmp/login-db.txt;
for PID in "${data[@]}"
do
  cat /tmp/login-db.txt | grep "dropbear\[$PID\]" > /tmp/login-db-pid.txt;
  NUM=`cat /tmp/login-db-pid.txt | wc -l`;
  USER=`cat /tmp/login-db-pid.txt | awk -F"for " '{print $2}' | awk '{print $1}'`;
  IP=`cat /tmp/login-db-pid.txt | awk -F"for " '{print $2}' | awk '{print $3}'`;
  if [ $NUM -eq 1 ]; then
    echo -e "${WHITE}$PID - $USER - $IP${RESET}";
  fi
done
garis
echo " "
garis
echo -e "  ${WHITE}  ID  |  Username  |  IP Address ${RESET}"
garis

cat $LOG | grep -i sshd | grep -i "Accepted password for" > /tmp/login-db.txt
data=( `ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'`);

for PID in "${data[@]}"
do
  cat /tmp/login-db.txt | grep "sshd\[$PID\]" > /tmp/login-db-pid.txt;
  NUM=`cat /tmp/login-db-pid.txt | wc -l`;
  USER=`cat /tmp/login-db-pid.txt | awk -F"for " '{print $2}' | awk '{print $1}'`;
  IP=`cat /tmp/login-db-pid.txt | awk -F"for " '{print $2}' | awk '{print $3}'`;
  if [ $NUM -eq 1 ]; then
    echo -e "${WHITE}$PID - $USER - $IP${RESET}";
  fi
done
garis
if [ -f "/etc/openvpn/server/openvpn-tcp.log" ]; then
  echo ""
  garis
  echo -e "  ${WHITE}  Username  |  IP Address  |  Connected ${RESET}"
  garis
  cat /etc/openvpn/server/openvpn-tcp.log | grep -w "^CLIENT_LIST" | cut -d ',' -f 2,3,8 | sed -e 's/,/      /g' > /tmp/vpn-login-tcp.txt
  cat /tmp/vpn-login-tcp.txt
fi
garis

if [ -f "/etc/openvpn/server/openvpn-udp.log" ]; then
  echo " "
  garis
  echo -e "    ${WHITE}sername  |  IP Address  |  Connected ${RESET}"
  garis
  cat /etc/openvpn/server/openvpn-udp.log | grep -w "^CLIENT_LIST" | cut -d ',' -f 2,3,8 | sed -e 's/,/      /g' > /tmp/vpn-login-udp.txt
  cat /tmp/vpn-login-udp.txt
fi
garis
echo ""