#!/bin/bash
clear

source /usr/bin/ui.sh

NAME=$(cat /etc/xray/username)

eval $(wget -qO- https://domainsaya.dekaa.my.id)
if ! command -v jq &> /dev/null; then
    echo -e "Tunggu sebentar proses. Menginstall Cloudflare..."
    apt install jq -y >/dev/null
fi
if [ ! -s /etc/apicf ]; then
  read -p "Masukkan token Cloudflare Anda: " input_token

  if [ -n "$input_token" ]; then
    echo "$input_token" > /etc/apicf
    export CF_KEY="$input_token"
  else
    echo "Tidak ada token dimasukkan, melanjutkan tanpa CF_KEY lokal."
    # CF_KEY akan tetap dari hasil eval (jika ada)
  fi
else
  CF_KEY=$(cat /etc/apicf)
  export CF_KEY
fi

clear
echo -e ""
banner "$NAME"
echo -e " "
read -p "DOMAIN    :  " lol
read -p "IP        :  " IP
echo -e ""
DO=$(echo "$lol" | cut -d "." -f2-)
SUB=$(echo "$lol" | cut -d "." -f1)
SUB_DOMAIN=${SUB}.${DO}
NS_DOMAIN=*.${SUB_DOMAIN}
set -euo pipefail
echo "Pointing Domain for $SUB_DOMAIN..."
ZONE=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DO}&status=active" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	RECORD=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${SUB_DOMAIN}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

		RECORD1=$(
		curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${NS_DOMAIN}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" | jq -r .result[0].id
	)

	if [[ "${#RECORD}" -le 10 ]]; then
		RECORD=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "Authorization: Bearer ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}' | jq -r .result.id
		)
	else
		RESULT=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}'
	)
	fi
		
	if [[ "${#RECORD1}" -le 10 ]]; then
		RECORD2=$(
			curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
			-H "Authorization: Bearer ${CF_KEY}" \
			-H "Content-Type: application/json" \
			--data '{"type":"A","name":"'${NS_DOMAIN}'","content":"'${IP}'","proxied":true}' | jq -r .result.id
		)
	else

	RESULT2=$(
		curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD1}" \
		-H "Authorization: Bearer ${CF_KEY}" \
		-H "Content-Type: application/json" \
		--data '{"type":"A","name":"'${NS_DOMAIN}'","content":"'${IP}'","proxied":true}'
	)	
	fi
clear
TIMES="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
TEXT="_______________________________
  POINTING DOMAIN BERHASIL 
_______________________________
  DOMAIN  : $SUB_DOMAIN 
  WILCARD : $NS_DOMAIN 
  IP      : <code>$IP</code> 
_______________________________
"
curl -s --max-time $TIMES -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null


Newbie_Banner_Log
garis_atas
echo -e "   ${WHITEBLD}  DOMAIN  : $SUB_DOMAIN $NC"
echo -e "   ${WHITEBLD}  WILCARD : $NS_DOMAIN $NC"
echo -e "   ${WHITEBLD}  IP      : $IP $NC"
garis_bawah
echo -e "[ ${BLUE}WARNING${NC} ] Do you want to Pointing Again ? (y/n)? "
read answer

# Memeriksa input jawaban
if [[ $answer =~ ^[Yy]$ ]]; then
    cf  # Panggil fungsi cf
else
    m-ftr  # Panggil fungsi utility
fi
